version: '3.8'
services:
  php-apache:
    container_name: php-apache
    build: apache-php
    volumes:
      - ./apache-php/src:/var/www/html-dynamic
    ports:
      - 8081:8081
  nginx:
    container_name: nginx
    build: nginx
    volumes:
      - ./nginx/src:/usr/share/nginx/html-static
    ports:
      - 8082:8082
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appDb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db/init.sql:/data/application/init.sql
      - db:/var/lib/mysql
    command: --init-file /data/application/init.sql
    ports:
      - 3306:3306
volumes:
  db:
