version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    build: .
    volumes:
      - ./src:/var/www/html
    ports:
      - 80:80
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appDb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./init.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    ports:
        - "3306:3306"
